services:
  - type: web
    name: admin-portal-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi_supabase.py
    envVars:
      - key: SUPABASE_DB_HOST
        value: db.sevlfbqydeludjfzatfe.supabase.co
      - key: SUPABASE_DB_NAME
        value: postgres
      - key: SUPABASE_DB_USER
        value: postgres
      - key: SUPABASE_DB_PASSWORD
        value: puravbhatt0504
      - key: SUPABASE_DB_PORT
        value: "5432"
